# Generated by Django 5.2.7 on 2026-06-12 11:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_librarycontentaccess'),
        ('progress', '0002_fix_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('points_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprogress',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verses_count', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_verses', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.verse')),
            ],
            options={
                'unique_together': {('user', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserSurahCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'surah')},
            },
        ),
    ]
