# Generated by Django 5.2.7 on 2026-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subadmin",
            field=models.BooleanField(default=False),
        ),
    ]
