# Generated by Django 5.2.7 on 2026-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_subadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_subadmin",
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
