# Generated by Django 5.2.7 on 2026-05-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("total_surahs", models.IntegerField(default=0)),
                ("total_verses", models.IntegerField(default=0)),
                ("total_reading_time", models.IntegerField(default=0)),
                ("total_reading_streak", models.IntegerField(default=0)),
                ("total_reading_target", models.IntegerField(default=0)),
                ("total_reading_days", models.IntegerField(default=0)),
                ("total_reading_days_streak", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(default="light", max_length=100)),
                ("language", models.CharField(default="en", max_length=100)),
                ("font_size", models.IntegerField(default=16)),
                ("font_family", models.CharField(default="Arial", max_length=100)),
                ("font_color", models.CharField(default="#000000", max_length=100)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=100),
                ),
                ("text_color", models.CharField(default="#000000", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("total_surahs", models.IntegerField(default=0)),
                ("total_verses", models.IntegerField(default=0)),
                ("total_reading_time", models.IntegerField(default=0)),
                ("total_reading_streak", models.IntegerField(default=0)),
                ("total_reading_target", models.IntegerField(default=0)),
                ("total_reading_days", models.IntegerField(default=0)),
                ("total_reading_days_streak", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
