# Generated by Django 5.2.7 on 2026-05-22 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_reading_days",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_reading_days_streak",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_reading_streak",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_reading_target",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_reading_time",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_surahs",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_users",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="total_verses",
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="actions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("delete", "Delete"),
                ],
                default="active",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="subscription_status",
            field=models.CharField(blank=True, default="free", max_length=100),
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usermanagement",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
