# Generated by Django 5.2.7 on 2026-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0002_remove_usermanagement_total_reading_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanagement",
            name="email",
            field=models.EmailField(blank=True, default="email", max_length=100),
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="username",
            field=models.CharField(blank=True, default="username", max_length=100),
        ),
    ]
