# Generated by Django 5.2.7 on 2026-05-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0003_usermanagement_email_usermanagement_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermanagement",
            name="email",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="username",
        ),
    ]
