# Generated by Django 5.2.7 on 2026-05-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0004_remove_usermanagement_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overview",
            old_name="total_reading_days",
            new_name="free_users",
        ),
        migrations.RenameField(
            model_name="overview",
            old_name="total_reading_days_streak",
            new_name="premium_users",
        ),
        migrations.RenameField(
            model_name="overview",
            old_name="total_reading_streak",
            new_name="revenue",
        ),
        migrations.RenameField(
            model_name="overview",
            old_name="total_reading_target",
            new_name="total_earn",
        ),
        migrations.RenameField(
            model_name="overview",
            old_name="total_reading_time",
            new_name="user_growth",
        ),
        migrations.RemoveField(
            model_name="overview",
            name="total_surahs",
        ),
        migrations.RemoveField(
            model_name="overview",
            name="total_verses",
        ),
    ]
