# Generated by Django 5.2.7 on 2026-05-22 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminDashboard",
            "0005_rename_total_reading_days_overview_free_users_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilesettings",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="font_color",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="font_family",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="language",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="text_color",
        ),
        migrations.RemoveField(
            model_name="profilesettings",
            name="theme",
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="is_subadmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profilesettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
