# Generated by Django 5.2.7 on 2026-05-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0007_librarycontent_subscriptionplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilesettings",
            name="is_subadmin",
        ),
    ]
