# Generated by Django 5.2.7 on 2026-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0008_remove_profilesettings_is_subadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='actions',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('suspend', 'Suspend'), ('delete', 'Delete')], default='active', max_length=100),
        ),
    ]
