# Generated by Django 5.2.7 on 2026-05-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="createcommunity",
            options={"verbose_name_plural": "communities"},
        ),
        migrations.AlterField(
            model_name="communitymembers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitemembers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymembers",
            unique_together={("community", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="invitemembers",
            unique_together={("community", "user")},
        ),
    ]
