# Generated by Django 5.2.7 on 2026-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcommunity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/'),
        ),
    ]
