# Generated by Django 6.0.5 on 2026-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
